language: node_js
node_js:
  - "4.2.2"
sudo: false
install:
  - npm install
  - npm run build
addons:
  sauce_connect:
    username: 'nteract-tester'
    access_key: 'b5ffd0eb-96e6-418d-9f15-3031cf8eb076'
